import "public/css/styles.css";
import React from "react";
import type { AppProps } from 'next/app';
import Head from "next/head";

const App = ({ Component, pageProps }: AppProps) => {
  return (
    <React.StrictMode>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <span className="w-full h-full p-0 m-0 bg-[#F9F7F5]">
        <Component {...pageProps} />
      </span>
    </React.StrictMode>
    );
};

export default App;

