import type { NextPage, InferGetStaticPropsType, GetStaticProps } from 'next';
import Head from 'next/head';
import { CarCarousel } from 'src/components/CarCarousel';
import { Car } from 'src/types/Car';

interface Props {
  carsData:  Car[];
}

export const getStaticProps: GetStaticProps<Props> = async ()  => {
  const { default: rawCarsData } = await import('public/api/cars.json');
  return {
    props: {
      carsData: rawCarsData.map(rawCar => ({
        ...rawCar,
        learnUrl: `/learn/${rawCar.id}`,
        shopUrl: `/shop/${rawCar.id}`,
      })),
    }
  }
}

const Home: NextPage<InferGetStaticPropsType<typeof getStaticProps>> = ({ carsData }) => {
  return (
    <div className="sm:m-6">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CarCarousel carsData={carsData} />
    </div>
  );
};

export default Home;
